export const assets = {
  images: {
    scooter: require("@/assets/images/icons/scooter.png"),
    boy: require("@/assets/images/icons/boy.png"),
    burger: require("@/assets/images/icons/burger.png"),
    bus: require("@/assets/images/icons/bus.png"),
    calendar: require("@/assets/images/icons/calendar-clock.png"),
    taxiCar: require("@/assets/images/icons/taxi-car.png"),
    car: require("@/assets/images/icons/car.png"),
    cocktail: require("@/assets/images/icons/wine.png"),
    flowers: require("@/assets/images/icons/flowers.png"),
    grocery: require("@/assets/images/icons/handbags.png"),
    package: require("@/assets/images/icons/box.png"),
    pharmacy: require("@/assets/images/icons/drug.png"),
    safetyCheckup: require("@/assets/images/icons/checkup.png"),
    restaurants: require("@/assets/images/icons/dish.png"),
    rocket: require("@/assets/images/icons/rocket.png"),
    privacyCheckup: require("@/assets/images/icons/lock.png"),
    taxiForTeens: require("@/assets/images/icons/taxi.png"),
    travel: require("@/assets/images/icons/globe-earth.png"),
    google: require("@/assets/images/icons/google-logo.png"),

    food1: require("@/assets/images/food/food-image-1.jpg"),
    food2: require("@/assets/images/food/food-image-2.jpg"),
    food3: require("@/assets/images/food/food-image-3.jpg"),
    food4: require("@/assets/images/food/food-image-4.jpg"),
    food5: require("@/assets/images/food/food-image-5.jpg"),
    food6: require("@/assets/images/food/food-image-6.jpg"),
    food7: require("@/assets/images/food/food-image-7.jpg"),
    food8: require("@/assets/images/food/food-image-8.jpg"),
    food9: require("@/assets/images/food/food-image-9.jpg"),
    food10: require("@/assets/images/food/food-image-10.jpg"),
    food11: require("@/assets/images/food/food-image-11.jpg"),
    food12: require("@/assets/images/food/food-image-12.jpg"),
  },
};
