import type { ActivityProps } from "@/components/Activity";

export const activities = [
  {
    type: "food",
    image: "food1",
    title: "Pancake House",
    date: new Date(2023, 5, 15, 10, 30),
    price: 24.12,
    currency: "USD",
    numberOfItems: 3,
  },
  {
    type: "ride",
    title: "123 Main St, Springfield",
    date: new Date(2023, 5, 14, 9, 15),
    price: 15.75,
    currency: "USD",
  },
  {
    type: "food",
    image: "food2",
    title: "Olive Garden",
    date: new Date(2023, 5, 13, 12, 45),
    price: 50.15,
    currency: "USD",
    numberOfItems: 2,
  },
  {
    type: "food",
    image: "food3",
    title: "Cassell's Hamburgers",
    date: new Date(2023, 5, 12, 14, 0),
    price: 75,
    currency: "USD",
    numberOfItems: 3,
  },
  {
    type: "ride",
    title: "456 Elm St, Metropolis",
    date: new Date(2023, 5, 11, 16, 30),
    price: 22.5,
    currency: "USD",
  },
  {
    type: "food",
    image: "food4",
    title: "LA Prime Steakhouse",
    date: new Date(2023, 5, 10, 18, 15),
    price: 120,
    currency: "USD",
    numberOfItems: 4,
  },
  {
    type: "food",
    image: "food5",
    title: "Wild Living Foods",
    date: new Date(2023, 5, 9, 20, 0),
    price: 23.99,
    currency: "USD",
    numberOfItems: 2,
  },
  {
    type: "ride",
    title: "789 Oak St, Gotham",
    date: new Date(2023, 5, 8, 21, 45),
    price: 18.0,
    currency: "USD",
  },
  {
    type: "food",
    image: "food6",
    title: "Doge toast",
    date: new Date(2023, 5, 7, 23, 30),
    price: 11.11,
    currency: "USD",
    numberOfItems: 1,
  },
  {
    type: "food",
    image: "food7",
    title: "WrapMe!",
    date: new Date(2023, 5, 6, 8, 0),
    price: 32.45,
    currency: "USD",
    numberOfItems: 2,
  },
  {
    type: "food",
    image: "food8",
    title: "Papa John's Pizza",
    date: new Date(2023, 5, 5, 7, 45),
    price: 75.25,
    currency: "USD",
    numberOfItems: 3,
  },
  {
    type: "ride",
    title: "101 Pine St, Star City",
    date: new Date(2023, 5, 4, 6, 30),
    price: 20.0,
    currency: "USD",
  },
  {
    type: "food",
    image: "food9",
    title: "Obi-wan pierogi",
    date: new Date(2023, 5, 3, 5, 15),
    price: 18.99,
    currency: "USD",
    numberOfItems: 1,
  },
  {
    type: "food",
    image: "food10",
    title: "Fishoria Fish and Chips",
    date: new Date(2023, 5, 2, 4, 0),
    price: 120,
    currency: "USD",
    numberOfItems: 4,
  },
  {
    type: "food",
    image: "food11",
    title: "Voodoo Donuts",
    date: new Date(2023, 5, 1, 3, 45),
    price: 60.2,
    currency: "USD",
    numberOfItems: 2,
  },
  {
    type: "food",
    image: "food12",
    title: "Indian Flame ",
    date: new Date(2023, 4, 30, 2, 30),
    price: 35.99,
    currency: "USD",
    numberOfItems: 2,
  },
] as ActivityProps[];
